image: continuumio/miniconda3:latest

variables:
  # Elastic
  TEXTA_ES_URL: http://172.17.0.1:9200
  # Redis
  TEXTA_REDIS_URL: redis://redis:6379
  # UAA
  TEXTA_USE_UAA: "True"
  TEXTA_UAA_REDIRECT_URI: http://localhost:8000/api/v1/uaa/callback
  TEXTA_UAA_USER: test1
  TEXTA_UAA_EMAIL: test1@test1.com
  TEXTA_UAA_PWD: test1
  TEXTA_UAA_URL: http://texta-uaa:8080/uaa
  TEXTA_UAA_AUTH_URL: http://texta-uaa:8080/uaa/oauth/authorize
  TEXTA_UAA_FRONT_REDIRECT_URL: http://localhost:4200/oauth
  TEXTA_UAA_CLIENT_ID: login
  TEXTA_UAA_CLIENT_SECRET: loginsecret
  # For keeping plots as artifacts
  TEXTA_TEST_KEEP_PLOT_FILES: "True"
  # Set admin password for tests
  #TEXTA_ADMIN_PASSWORD: "1234"

services:
  - name: redis:latest
  - name: docker.texta.ee/texta/texta-uaa:latest
    alias: texta-uaa

stages:
  - test
  - build

Test:
  before_script:
    - apt-get install curl -y
    - conda env create -f environment-nogpu.yaml && source activate texta-rest
    - python import_test_data.py -es $TEXTA_ES_URL
    - python migrate.py
  stage: test
  tags:
    - ci-test
  artifacts:
    paths:
      - data/media
    expire_in: 1 week
  script:
    - sh wait-for-uaa.sh
    - python manage.py test
  only:
    - master
    - merge_requests

Build:
  stage: build
  tags:
    - docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
    - sh ./docker/build_and_push.sh
    - docker system prune --volumes -f
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.texta.ee/api/v4/projects/84/trigger/pipeline
  only:
    - tags
