image: python:3.6

services:
  - docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
  - redis:latest

before_script:
  - python -V
  - pip install -r requirements.txt
  - python migrate.py

stages:
  - test

Test:
  stage: test
  tags:
  - ci-test
  script:
  - python manage.py test
