image: python:3.6

services:
  - docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
  - redis:latest

before_script:
  - python -V
  - pip install -r requirements.txt
  - python import_test_index.py -es http://elasticsearch:9200
  - python migrate.py

stages:
  - test

Test:
  stage: test
  tags:
  - ci-test
  variables:
    TEXTA_ES_URL: http://elasticsearch:9200
    TEXTA_REDIS_URL: redis://redis:6379
  script:
  - python manage.py test
