image: continuumio/miniconda3:latest

variables:
  # Elastic
  TEXTA_ES_URL: http://elastic-dev.texta.ee:9200
  # Redis
  TEXTA_REDIS_URL: redis://redis:6379
  # UAA
  TEXTA_USE_UAA: "True"
  TEXTA_UAA_REDIRECT_URI: http://localhost:8000/api/v1/uaa/callback
  TEXTA_UAA_USER: test1
  TEXTA_UAA_EMAIL: test1@test1.com
  TEXTA_UAA_PWD: test1
  TEXTA_UAA_URL: http://texta-uaa:8080/uaa
  TEXTA_UAA_AUTH_URL: http://texta-uaa:8080/uaa/oauth/authorize
  TEXTA_UAA_FRONT_REDIRECT_URL: http://localhost:4200/oauth
  TEXTA_UAA_CLIENT_ID: login
  TEXTA_UAA_CLIENT_SECRET: loginsecret
  # For keeping plots as artifacts
  TEXTA_TEST_KEEP_PLOT_FILES: "True"
  # Set admin password for tests
  #TEXTA_ADMIN_PASSWORD: "1234"
  # MLP lang codes
  TEXTA_LANGUAGE_CODES: et,en
  TEXTA_EXTERNAL_DATA_DIR: /cache

services:
  - name: redis:latest
  - name: docker.texta.ee/texta/texta-uaa:latest
    alias: texta-uaa

stages:
  - test
  - build-test
  - build-final


Test:
  # Tests back-end locally
  before_script:
    - apt-get install curl cmake build-essential -y
    - conda env create -f environment-nogpu.yaml && source activate texta-rest
    - python import_test_data.py -es $TEXTA_ES_URL
    - python migrate.py
  stage: test
  tags:
    - ci-test
  script:
    - sh wait-for-uaa.sh
    - python manage.py test


Build-Test:
  # Builds back image for front tests
  stage: build-test
  tags:
    - docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee  
    - docker build --compress --force-rm --no-cache -t docker.texta.ee/texta/texta-rest/test-rest:latest -f ./docker/Dockerfile .
    - docker push docker.texta.ee/texta/texta-rest/texta-test:latest


Build:
  # Builds final image with new front
  stage: build-final
  tags:
    - docker
  trigger:
    - texta/texta-rest-front
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
    #- sh ./docker/build_and_push.sh
    #- docker system prune --volumes -f
  #only:
  #  - tags
