image: python:3.6

services:
  - mysql:5.7
  - docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2

before_script:
  - python -V
  - pip install -r requirements.txt

stages:
  - test

Test:
  stage: test
  tags:
  - test-ci
  script:
  - python manage.py test
