image: continuumio/miniconda3:latest

services:
  - name: redis:latest

stages:
  - test
  - build

Test:
  before_script:
    - conda env create -f environment-nogpu.yaml && source activate texta-rest
    - python import_test_data.py -es http://elastic-dev.texta.ee:9200
    - python migrate.py
  stage: test
  tags:
  - ci-test
  variables:
    TEXTA_ES_URL: http://elastic-dev.texta.ee:9200
    TEXTA_REDIS_URL: redis://redis:6379
  script:
  - python manage.py test

Build:
  stage: build
  tags:
  - docker
  script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
  - python ./docker/build_and_push.py
  - docker system prune --volumes -f
  - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.texta.ee/api/v4/projects/84/trigger/pipeline
  only:
  - tags