image: python:3.6

tags:
  - ci-test

services:
  - mysql:5.7
  - docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  script:
  - python manage.py test
