image: python:3.6

services:
  - name: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    alias: elasticsearch
  - redis:latest

before_script:
  stage: test
  script:
    - python -V
    - pip install -r requirements.txt
    - python import_test_index.py -es http://elasticsearch:9200
    - python migrate.py

stages:
  - test
  - build

Test:
  stage: test
  tags:
  - ci-test
  variables:
    TEXTA_ES_URL: http://elasticsearch:9200
    TEXTA_REDIS_URL: redis://redis:6379
  script:
  - python manage.py test

Build:
  stage: build
  tags:
  - docker
  script:
  - docker build -t docker.texta.ee/texta/texta-rest:latest .