image: continuumio/miniconda3:latest

services:
  - name: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    alias: elasticsearch
  - name: docker.texta.ee/texta/mlp:latest
    alias: texta-mlp
  - name: redis:latest

stages:
  - test
  - build

Test:
  before_script:
    - sed -i '/  - tensorflow-gpu/c\  - tensorflow' environment.yaml
    - conda env create -f environment.yaml && source activate texta-rest
    - python import_test_index.py -es http://elasticsearch:9200
    - python migrate.py
  stage: test
  tags:
  - ci-test
  variables:
    TEXTA_ES_URL: http://elasticsearch:9200
    TEXTA_MLP_URL: http://texta-mlp:5000
    TEXTA_REDIS_URL: redis://redis:6379
  script:
  - python manage.py test
  except:
  - tags

Build:
  stage: build
  tags:
  - docker
  before_script:
    - pip install requests
  script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
  - python ./docker/build_and_push.py
  only:
  - tags