version: '3'

services:

#  elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
#    ports:
#      - 9200
#    environment:
#     - bootstrap.memory_lock=true
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./docker/conf/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./data-volumes/elastic-data:/usr/share/elasticsearch/data
#      - ./data-volumes/elastic-logs:/usr/share/elasticsearch/logs

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data-volumes/postgres:/var/lib/postgresql/data

  toolkit-rest:
    container_name: toolkit-rest
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:8000
    env_file:
      - ./docker/conf/.env
    volumes:
      - ./data-volumes/toolkit-data:/var/texta-rest/data
    depends_on:
      - postgres
#      - elasticsearch
