version: '3'

services:

  elasticsearch:
    container_name: elasticsearch
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    ports:
      - 9200:9200
    environment:
     - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  redis:
    container_name: redis
    image: redis
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres:/var/lib/postgresql/data

  toolkit-rest:
    container_name: toolkit-rest
    image: texta-rest:latest
    ports:
      - 8000:80
    env_file:
      - ./docker/conf/.env
    volumes:
      - toolkit-data:/var/texta-rest/data
    depends_on:
      - postgres
      - elasticsearch

volumes:
  elastic-data:
  toolkit-data:
  postgres:
