version: '3'

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    ports:
      - 9200:9200
    environment:
     - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  toolkit-rest:
#    container_name: toolkit-rest
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    ports:
#      - 80:8000
#    env_file:
#      - ./docker/conf/.env
#    volumes:
#      - ./data-volumes/toolkit-data:/var/texta-rest/data
#    depends_on:
#      - postgres
#      - elasticsearch

volumes:
  elastic-data:
  postgres-data:
