version: '3'

services:
  
  texta-elasticsearch:
    container_name: texta-elasticsearch
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
  
  texta-redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
  
  texta-postgres:
    container_name: texta-postgres
    image: postgres:11
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  texta-rest:
    container_name: texta-rest
    image: docker.texta.ee/texta/texta-rest:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
    env_file:
      - ./docker/conf/env
    volumes:
      - toolkit-data:/var/texta-rest/data
    depends_on:
      - texta-postgres
      - texta-elasticsearch

volumes:
  elastic-data:
  toolkit-data:
  postgres-data:
