name: texta-rest

channels:
  - conda-forge
  - anaconda

dependencies:
  - nomkl
  - python=3.6
  - pip
  - keras==2.2.*
  - pandas
  - scikit-learn
  - matplotlib
  - graphviz
  - gensim==3.7.*
  - pydot
  - psutil
  - redis
  - uwsgi
  - supervisor
  - psycopg2
  - mysql-connector-python
  - pip:
    - tensorflow==1.5.0
    - django==2.1.*
    - djangorestframework==3.9.*
    - celery==4.2.*
    - elasticsearch==6.3.*
    - redis==3.2.*
    - django-multiselectfield
    - drf-nested-routers
    - django-rest-auth[with_social]
    - termcolor
    - django-extensions
    - joblib
    - django-rest-serializer-field-permissions
    - django-cors-headers
    - sentencepiece
    - python-json-logger
    - drf-yasg
