name: texta-rest

channels:
  - conda-forge
  - anaconda
  - bioconda
  - menpo

dependencies:
  - python=3.7
  - pip
  - pandas=1.1.5
  - scikit-learn==0.22.*
  - matplotlib
  - graphviz
  - gensim==3.*
  - pydot
  - psutil
  - pynvml
  - uwsgi
  - nginx
  - supervisor
  - psycopg2
  - mysqlclient
  - pip:
      - django==2.*
      - django-multiselectfield
      - django-rest-serializer-field-permissions
      - django-cors-headers
      - django-extensions
      - django-filter
      - django-rest-auth[with_social]
      - djangorestframework==3.11.*
      - drf-nested-routers
      - celery==4.*
      - redis==3.*
      - elasticsearch>7<8
      - elasticsearch_dsl>7<8
      - termcolor
      - joblib
      - python-json-logger
      - drf-yasg
      - xlrd==1.2.0
      - dill
      - texta-anonymizer==1.*
      - texta-mlp>=1.9.1
      - texta-lexicon-matcher==1.*
      - texta-tools==1.*
      - texta-tagger==1.3.*
      - texta-torch-tagger==1.*
      - texta-bert-tagger==2.3.*
      - texta-face-analyzer==0.*
      - torchtext==0.6.*
      - torch==1.5.0+cpu
      - -f https://download.pytorch.org/whl/torch_stable.html
      - pyjwt<2
      - beautifulsoup4
      - nltk==3.6.*
