name: texta-rest

channels:
  - conda-forge
  - anaconda
  - bioconda

dependencies:
  - python=3.6
  - pip
  - tensorflow-gpu
  - keras==2.2.*
  - mkl
  - pandas
  - scikit-learn
  - matplotlib
  - graphviz
  - gensim==3.7.*
  - pydot
  - psutil
  - redis
  - uwsgi
  - supervisor
  - psycopg2
  - mysqlclient
  - pip:
    - django==2.1.*
    - djangorestframework==3.9.*
    - celery==4.2.*
    - elasticsearch==6.3.*
    - redis==3.2.*
    - django-multiselectfield
    - drf-nested-routers
    - django-rest-auth[with_social]
    - termcolor
    - django-extensions
    - joblib
    - django-rest-serializer-field-permissions
    - django-cors-headers
    - elasticsearch_dsl<7
    - sentencepiece
    - python-json-logger
    - drf-yasg
