name: texta-rest

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.6
  - pip
  - tensorflow-gpu
  - keras
  - mkl
  - pandas
  - scikit-learn
  - matplotlib
  - graphviz
  - gensim==3.7.1
  - pydot
  - psutil
  - redis
  - nginx
  - uwsgi
  - supervisor
  - psycopg2
  - pip:
    - django==2.1.7
    - djangorestframework==3.9.2
    - celery==4.2.2
    - elasticsearch==6.3.1
    - redis==3.2.1
    - django-multiselectfield
    - drf-nested-routers
    - django-rest-auth[with_social]
    - termcolor
    - django-extensions
    - joblib
    - django-rest-serializer-field-permissions
    - django-cors-headers
    - sentencepiece
