name: texta-rest

channels:
  - conda-forge
  - anaconda
  - bioconda
  - pytorch

dependencies:
  - python=3.6
  - pip
  - pandas
  - scikit-learn==0.*
  - matplotlib
  - graphviz
  - gensim==3.*
  - pydot
  - psutil
  - uwsgi
  - nginx
  - supervisor
  - psycopg2
  - mysqlclient
  - pytorch
  - pip:
      - django==2.*
      - django-multiselectfield
      - django-rest-serializer-field-permissions
      - django-cors-headers
      - django-extensions
      - django-filter
      - django-rest-auth[with_social]
      - http://pypi.texta.ee/texta-mlp/texta-mlp-1.3.5.tar.gz
      - http://pypi.texta.ee/texta-lexicon-matcher/texta-lexicon-matcher-1.0.2.tar.gz
      - djangorestframework==3.*
      - drf-nested-routers
      - celery==4.*
      - redis==3.*
      - elasticsearch<7
      - elasticsearch_dsl<7
      - termcolor
      - joblib
      - python-json-logger
      - drf-yasg
      - torchtext
      - xlrd
      - dill
      - https://pypi.texta.ee/texta-anonymizer/texta-anonymizer-1.0.0.tar.gz
