# Generated by Django 2.2.19 on 2021-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bert_tagger', '0004_berttagger_pos_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berttagger',
            name='pos_label',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
