# Generated by Django 2.2.19 on 2021-06-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bert_tagger', '0005_auto_20210621_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berttagger',
            name='pos_label',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
