# Generated by Django 2.2.28 on 2023-01-17 12:07
import json

from django.db import migrations, models


def transfer_old_category_values(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Labelset = apps.get_model('annotator', 'Labelset')
    for labelset in Labelset.objects.all():
        labelset._category = labelset.category.value
        labelset.save()


def transfer_old_label_values(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Labelset = apps.get_model('annotator', 'Labelset')
    for labelset in Labelset.objects.all():
        labels = [label.value for label in labelset.values.all()]
        labelset._values = json.dumps(labels, ensure_ascii=False)
        labelset.save()


class Migration(migrations.Migration):
    dependencies = [
        ('annotator', '0016_char_length_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelset',
            name='_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='labelset',
            name='_values',
            field=models.TextField(default='[]'),
        ),

        migrations.RunPython(transfer_old_category_values),

        migrations.RunPython(transfer_old_label_values),

        migrations.RemoveField(
            model_name='labelset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labelset',
            name='values',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Label',
        ),

        migrations.RenameField(
            model_name='labelset',
            old_name='_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='labelset',
            old_name='_values',
            new_name='values',
        ),
    ]
