# Generated by Django 2.2.28 on 2023-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0017_change_labels_to_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='document_uuid',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
