# Generated by Django 2.2.28 on 2023-01-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0018_comment_document_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='use_shared_comments',
            field=models.BooleanField(default=False),
        ),
    ]
