# Generated by Django 2.2.28 on 2023-01-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0019_annotator_use_shared_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='document_uuid',
            field=models.CharField(default=None, help_text='Reference UUID for the original document.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='document_id',
            field=models.CharField(db_index=True, help_text='Elasticsearch document ID for the sub-index.', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='fact_id',
            field=models.TextField(db_index=True, default=None, help_text='UUID of the Texta Fact, useful for editing later.', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='index',
            field=models.CharField(help_text='Which Elasticsearch index does the document live in.', max_length=255),
        ),
    ]
