# Generated by Django 2.2.19 on 2021-03-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_auto_20210317_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='binary_scores',
            field=models.TextField(default='{}'),
        ),
    ]
