# Generated by Django 2.2.19 on 2021-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_evaluator_evaluation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='plot',
            field=models.FileField(null=True, upload_to='data/media', verbose_name=''),
        ),
    ]
