# Generated by Django 2.2.19 on 2021-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_evaluator_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='document_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='scores_imprecise',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
