# Generated by Django 2.2.19 on 2021-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_evaluator_add_individual_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='binary_scores',
        ),
        migrations.AddField(
            model_name='evaluator',
            name='individual_results',
            field=models.TextField(default='{}'),
        ),
    ]
