# Generated by Django 2.2.19 on 2021-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_auto_20210323_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='memory_buffer',
            field=models.FloatField(default=2, null=True),
        ),
    ]
