# Generated by Django 2.2.22 on 2021-06-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0013_auto_20210615_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyesanalyzerworker',
            name='strip_html',
            field=models.BooleanField(default=True),
        ),
    ]
